function f = fsys(X,u,p,region)
j = u(1);
kappa = u(2);
sr = X(1);
v = X(2);
a = X(3);
dr = X(4);
psir = X(5);

switch region
    case 1 % Gerade
        f = [v*cos(psir)/(1-dr*p.kapparef_straight);...
    a;...
    j;...
    v*sin(psir);...
    kappa*v - p.kapparef_straight*v*cos(psir)/(1-dr*p.kapparef_straight)];
    case 2 % Kurve
        f = [v*cos(psir)/(1-dr*p.kapparef_curve);...
    a;...
    j;...
    v*sin(psir);...
    kappa*v - p.kapparef_curve*v*cos(psir)/(1-dr*p.kapparef_curve)];
end
end