function f = kangln(X,u,p,region)
j = u(1);
kappa = u(2);
sr = X(1);
v = X(2);
a = X(3);
dr = X(4);
psir = X(5);
l1 = X(6);
l2 = X(7);
l3 = X(8);
l4 = X(9);
l5 = X(10);

switch region
    case 1 % Gerade
        switch p.use_dr
            case 1
                % Bestrafung von dr im Gütefunktional
                f = [0;...
            -(2*p.fy*v^3*kappa^2 + l1*cos(psir)/(1-dr*p.kapparef_straight) + l4*sin(psir) + l5*kappa - l5*p.kapparef_straight*cos(psir)/(1-dr*p.kapparef_straight));...
            -(p.fa*a + l2);...
            -(p.fr*dr + p.kapparef_straight*l1*v*cos(psir)/(1-dr*p.kapparef_straight)^2 - p.kapparef_straight^2*l5*v*cos(psir)/(1-dr*p.kapparef_straight)^2);...
            -(l4*v*cos(psir) - l1*v*sin(psir)/(1-dr*p.kapparef_straight) + p.kapparef_straight*l5*v*sin(psir)/(1-dr*p.kapparef_straight))];
            case 0
                % ohne Zustandsbestrafung im Gütefunktional
                f = [0;...
            -(2*p.fy*v^3*kappa^2 + l1*cos(psir)/(1-dr*p.kapparef_straight) + l4*sin(psir) + l5*kappa - l5*p.kapparef_straight*cos(psir)/(1-dr*p.kapparef_straight));...
            -(p.fa*a + l2);...
            -(p.kapparef_straight*l1*v*cos(psir)/(1-dr*p.kapparef_straight)^2 - p.kapparef_straight^2*l5*v*cos(psir)/(1-dr*p.kapparef_straight)^2);...
            -(l4*v*cos(psir) - l1*v*sin(psir)/(1-dr*p.kapparef_straight) + p.kapparef_straight*l5*v*sin(psir)/(1-dr*p.kapparef_straight))];
        end
    case 2 % Kurve
        switch p.use_dr
            case 1
                 % Bestrafung von dr im Gütefunktional
                 f = [0;...
            -(2*p.fy*v^3*kappa^2 + l1*cos(psir)/(1-dr*p.kapparef_curve) + l4*sin(psir) + l5*kappa - l5*p.kapparef_curve*cos(psir)/(1-dr*p.kapparef_curve));...
            -(p.fa*a + l2);...
            -(p.fr*dr + p.kapparef_curve*l1*v*cos(psir)/(1-dr*p.kapparef_curve)^2 - p.kapparef_curve^2*l5*v*cos(psir)/(1-dr*p.kapparef_curve)^2);...
            -(l4*v*cos(psir) - l1*v*sin(psir)/(1-dr*p.kapparef_curve) + p.kapparef_curve*l5*v*sin(psir)/(1-dr*p.kapparef_curve))];
            case 0
                % ohne Zustandsbestrafung im Gütefunktional
                f = [0;...
            -(2*p.fy*v^3*kappa^2 + l1*cos(psir)/(1-dr*p.kapparef_curve) + l4*sin(psir) + l5*kappa - l5*p.kapparef_curve*cos(psir)/(1-dr*p.kapparef_curve));...
            -(p.fa*a + l2);...
            -(p.kapparef_curve*l1*v*cos(psir)/(1-dr*p.kapparef_curve)^2 - p.kapparef_curve^2*l5*v*cos(psir)/(1-dr*p.kapparef_curve)^2);...
            -(l4*v*cos(psir) - l1*v*sin(psir)/(1-dr*p.kapparef_curve) + p.kapparef_curve*l5*v*sin(psir)/(1-dr*p.kapparef_curve))];
        end
end
end