function res = bcfcn_free_tf(X0,Xf,param,p)
delta_t = param; 
srf = Xf(1);
vf = Xf(2);
af = Xf(3);
drf = Xf(4);
psirf = Xf(5);
l1f = Xf(6);
l2f = Xf(7);
l3f = Xf(8);
l4f = Xf(9);
l5f = Xf(10);
uf = uopt(Xf,p);
jf = uf(1);
kappaf = uf(2);

% H(tf)+1=0 ohne Zustandsbestrafung im Gütefunktional
% J=tf+int(1/2*fj*j^2+1/2*fa*a^2+1/2*fy*kappa^2*v^4)
H_tf = 1/2*p.fj*jf^2 + 1/2*p.fa*af^2 + 1/2*p.fy*kappaf^2*vf^4 + l1f*vf*cos(psirf)/(1-drf*p.kapparef) + l2f*af + l3f*jf + l4f*vf*sin(psirf) + ...
    l5f*vf*(kappaf - p.kapparef*cos(psirf)/(1-drf*p.kapparef));

% H(tf)+1=0 Bestrafung von dr im Gütefunktional
% J=tf+int(1/2*fj*j^2+1/2*fa*a^2+1/2*fy*kappa^2*v^4+1/2*fr*dr^2)
H_tf = 1/2*p.fr*drf^2 + 1/2*p.fj*jf^2 + 1/2*p.fa*af^2 + 1/2*p.fy*kappaf^2*vf^4 + l1f*vf*cos(psirf)/(1-drf*p.kapparef) + l2f*af + l3f*jf + l4f*vf*sin(psirf) + ...
    l5f*vf*(kappaf - p.kapparef*cos(psirf)/(1-drf*p.kapparef));

% sf, drf, psirf sind festgelegt, vf und af sind frei
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     X0(5) - p.x0(5);...
%     srf - p.sf;...
%     drf - p.drf;...
%     psirf - p.psirf;...
%     l2f;...
%     l3f;...
%     H_tf + 1];

% nur sf ist festgelegt, vf, af, drf und psirf sind frei
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     X0(5) - p.x0(5);...
%     srf - p.sf;...
%     l2f;...
%     l3f;...
%     l4f;...
%     l5f;...
%     H_tf + 1];

% sf und psirf sind festgelegt, vf, af und drf sind frei
res = [X0(1) - p.x0(1);...
    X0(2) - p.x0(2);...
    X0(3) - p.x0(3);...
    X0(4) - p.x0(4);...
    X0(5) - p.x0(5);...
    srf - p.sf;...
    psirf - p.psirf;...
    l2f;...
    l3f;...
    l4f;...
    H_tf + 1];

% sf und drf sind festgelegt, vf, af und psirf sind frei, macht keinen Sinn,
% weil psirf nicht frei sein darf
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     X0(5) - p.x0(5);...
%     srf - p.sf;...
%     drf - p.drf;...
%     l2f;...
%     l3f;...
%     l5f;...
%     H_tf + 1];
end
