function y = guess_free_tf(x)
y = [zeros(1,length(x));...
    ones(1,length(x));...
    zeros(1,length(x));...
    zeros(1,length(x));...
    zeros(1,length(x));...
    zeros(1,length(x));...
    zeros(1,length(x));...
    zeros(1,length(x))];
end
