function dXdt = bvpfcn_free_tf(t,X,param,p) % equation to solve
dXdt = zeros(8,1);
dXdt = param*[X(2)*cos(X(4))/(1-X(3)*p.kapparef);...
    -X(6)/p.fx;...
    X(2)*sin(X(4));...
    -X(8)/(p.fy*X(2)^2) - p.kapparef*X(2)*cos(X(4))/(1-X(3)*p.kapparef);...
    0;...
    -2*X(8)^2/(p.fy*X(2)^2) - X(5)*cos(X(4))/(1-X(3)*p.kapparef) - X(7)*sin(X(4)) + X(8)^2/(p.fy*X(2)^3) + X(8)*p.kapparef*cos(X(4))/(1-X(3)*p.kapparef);...
    -p.fr*X(3) - p.kapparef*X(5)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2 + p.kapparef^2*X(8)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2;...
    X(5)*X(2)*sin(X(4))/(1-X(3)*p.kapparef) - X(7)*X(2)*cos(X(4)) - p.kapparef*X(8)*X(2)*sin(X(4))/(1-X(3)*p.kapparef)];
end