function res = bcfcn_free_tf(XL,XR,param,p)
nu_tilde = param(1);
delta_t1 = param(2);
delta_t2 = param(3);

X0 = XL(:,1);
Xf = XR(:,end);
X_internalGNB_L = XL(:,end);
X_internalGNB_R = XR(:,1);

% Endzustand
srf = Xf(1);
vf = Xf(2);
drf = Xf(3);
psirf = Xf(4);
l1f = Xf(5);
l2f = Xf(6);
l3f = Xf(7);
l4f = Xf(8);


% Stellgrößen tf, Kurve
uf = uopt(Xf,p);
axf = uf(1);
kappaf = uf(2);

% linker Randzustand von t1
sL = X_internalGNB_L(1);
vL = X_internalGNB_L(2);
drL = X_internalGNB_L(3);
psirL = X_internalGNB_L(4);
l1L = X_internalGNB_L(5);
l2L = X_internalGNB_L(6);
l3L = X_internalGNB_L(7);
l4L = X_internalGNB_L(8);

% rechter Randzustand von t1
sR = X_internalGNB_R(1);
vR = X_internalGNB_R(2);
drR = X_internalGNB_R(3);
psirR = X_internalGNB_R(4);
l1R = X_internalGNB_R(5);
l2R = X_internalGNB_R(6);
l3R = X_internalGNB_R(7);
l4R = X_internalGNB_R(8);

% Stellgrößen linker und rechter Rand von t1
uL = uopt(X_internalGNB_L,p);
axL = uL(1);
kappaL = uL(2); 

uR = uopt(X_internalGNB_R,p);
axR = uR(1);
kappaR = uR(2); 

switch p.use_dr
    case 1
        % H(tf)+1=0 mit Zustandsbestrafung im Gütefunktional
        % J=tf+int(1/2*fx*ax^2+1/2*fy*kappa^2*v^4+1/2*fr*dr^2)
        H_tf = 1/2*p.fr*drf^2 + 1/2*p.fx*axf^2 + 1/2*p.fy*kappaf^2*vf^4 + ...
            l1f*vf + l2f*axf + l3f*vf*sin(psirf) + l4f*vf*(kappaf - p.kapparef_curve*cos(psirf)/(1-drf*p.kapparef_curve));
        H_L = 1/2*p.fr*drL^2 + 1/2*p.fx*axL^2 + 1/2*p.fy*kappaL^2*vL^4 + ...
            l1L*vL + l2L*axL + l3L*vL*sin(psirL) + l4L*vL*(kappaL - p.kapparef_straight*cos(psirL)/(1-drL*p.kapparef_straight));
        H_R = 1/2*p.fr*drR^2 + 1/2*p.fx*axR^2 + 1/2*p.fy*kappaR^2*vR^4 + ...
            l1R*vR + l2R*axR + l3R*vR*sin(psirR) + l4R*vR*(kappaR - p.kapparef_curve*cos(psirR)/(1-drR*p.kapparef_curve));
    case 0
        % H(tf)+1=0 ohne Zustandsbestrafung im Gütefunktional
        % J=tf+int(1/2*fx*ax^2+1/2*fy*kappa^2*v^4)
        H_tf = 1/2*p.fx*axf^2 + 1/2*p.fy*kappaf^2*vf^4 + ...
            l1f*vf + l2f*axf + l3f*vf*sin(psirf) + l4f*vf*(kappaf - p.kapparef_curve*cos(psirf)/(1-drf*p.kapparef_curve));
        H_L = 1/2*p.fx*axL^2 + 1/2*p.fy*kappaL^2*vL^4 + ...
            l1L*vL + l2L*axL + l3L*vL*sin(psirL) + l4L*vL*(kappaL - p.kapparef_straight*cos(psirL)/(1-drL*p.kapparef_straight));
        H_R = 1/2*p.fx*axR^2 + 1/2*p.fy*kappaR^2*vR^4 + ...
            l1R*vR + l2R*axR + l3R*vR*sin(psirR) + l4R*vR*(kappaR - p.kapparef_curve*cos(psirR)/(1-drR*p.kapparef_curve));
end

% sf ist festgelegt, vf, drf, psirf sind frei
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     srf - p.sf;...
%     l2f;...
%     l3f;...
%     l4f;...
%     H_tf + 1;...
%     sL - sR;... % Stetigkeit am internen Randwert
%     vL - vR;...
%     drL - drR;...
%     psirL - psirR;...
%     l1L - l1R - 2*nu_tilde;... % Transversalitätsbedingung für l1 (l1(t1-) = l1(t1+) + dg/dx|t1*nu_tilde)
%     l2L - l2R;...
%     l3L - l3R;...
%     l4L - l4R;...
%     sL - p.s1;... % zusätzliche interne Randbedingung
%     H_L - H_R - 0]; % Transversalitätsbedingung für Umschaltpunkt

% sf, drf, psirf sind festgelegt, vf ist frei
res = [X0(1) - p.x0(1);...
    X0(2) - p.x0(2);...
    X0(3) - p.x0(3);...
    X0(4) - p.x0(4);...
    srf - p.sf;...
    drf - p.drf;...
    psirf - p.psirf;...
    l2f;...
    H_tf + 1;...
    sL - sR;... % Stetigkeit am internen Randwert
    vL - vR;...
    drL - drR;...
    psirL - psirR;...
    l1L - l1R - 2*nu_tilde;... % Transversalitätsbedingung für l1 (l1(t1-) = l1(t1+) + dg/dx|t1*nu_tilde)
    l2L - l2R;...
    l3L - l3R;...
    l4L - l4R;...
    sL - p.s1;... % zusätzliche interne Randbedingung
    H_L - H_R - 0]; % Transversalitätsbedingung für Umschaltpunkt

% sf, psirf sind festgelegt, vf, drf sind frei
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     srf - p.sf;...
%     psirf - p.psirf;...
%     l2f;...
%     l3f;
%     H_tf + 1;...
%     sL - sR;... % Stetigkeit am internen Randwert
%     vL - vR;...
%     drL - drR;...
%     psirL - psirR;...
%     l1L - l1R - 2*nu_tilde;... % Transversalitätsbedingung für l1 (l1(t1-) = l1(t1+) + dg/dx|t1*nu_tilde)
%     l2L - l2R;...
%     l3L - l3R;...
%     l4L - l4R;...
%     sL - p.s1;... % zusätzliche interne Randbedingung
%     H_L - H_R - 0]; % Transversalitätsbedingung für Umschaltpunkt
end
