function res = bcfcn_fix_tf(X0,Xf,p)
res = [X0(1) - p.x0(1);...
    X0(2) - p.x0(2);...
    X0(3) - p.x0(3);...
    X0(4) - p.x0(4);...
    Xf(1) - p.sf;...
    Xf(3) - p.drf;...
    Xf(4) - p.psirf;...
    Xf(6)];
end