function dXdt = myodefun_extended(t,X,p)
v = X(1); dr = X(2); psir = X(3); l1 = X(4); l2 = X(5); l3 = X(6); l4 = X(7); 
ax = -l2/p.fx; kappa = -l4/(p.fy*v^3);
    dXdt = [ax;...
        v*sin(psir);...
        kappa*v - p.kapparef*v*cos(psir)/(1-dr*p.kapparef);...
        0;...
        -(2*p.fy*kappa^2*v^3 + l1*cos(psir)/(1-dr*p.kapparef) + l3*sin(psir) + l4*kappa - l4*p.kapparef*cos(psir)/(1-dr*p.kapparef));...
        -(l1*v*p.kapparef*cos(psir)/(1-dr*p.kapparef)^2 - l4*v*p.kapparef^2*cos(psir)/(1-dr*p.kapparef)^2);...
        -(l3*v*cos(psir) - l1*v*sin(psir)/(1-dr*p.kapparef) + l4*v*p.kapparef*sin(psir)/(1-dr*p.kapparef))
        ];
end