function res = bcfcn_free_tf(X0,Xf,param,p)

srf = Xf(1);
vf = Xf(2);
drf = Xf(3);
psirf = Xf(4);
l1f = Xf(5);
l2f = Xf(6);
l3f = Xf(7);
l4f = Xf(8);
uf = uopt(Xf,p);
axf = uf(1);
kappaf = uf(2);

% H(tf)+1=0 ohne Zustandsbestrafung im Gütefunktional
% J=tf+int(1/2*fx*ax^2+1/2*fy*kappa^2*v^4)
% H_tf = 1/2*p.fx*axf^2 + 1/2*p.fy*kappaf^2*vf^4 + l1f*vf*cos(psirf)/(1-drf*p.kapparef) + l2f*axf + l3f*vf*sin(psirf) + ...
%     l4f*vf*(kappaf - p.kapparef*cos(psirf)/(1-drf*p.kapparef));

% H(tf)+1=0 Bestrafung von dr im Gütefunktional
% J=tf+int(1/2*fr*dr^2+1/2*fx*ax^2+1/2*fy*kappa^2*v^4)
H_tf = 1/2*p.fr*drf^2 + 1/2*p.fx*axf^2 + 1/2*p.fy*kappaf^2*vf^4 + l1f*vf*cos(psirf)/(1-drf*p.kapparef) + l2f*axf + l3f*vf*sin(psirf) + ...
    l4f*vf*(kappaf - p.kapparef*cos(psirf)/(1-drf*p.kapparef));

% H(tf)+1=0 Bestrafung von psir im Gütefunktional
% J=tf+int(1/2*fp*psir^2+1/2*fx*ax^2+1/2*fy*kappa^2*v^4)
% H_tf = 1/2*p.fp*psirf^2 + 1/2*p.fx*axf^2 + 1/2*p.fy*kappaf^2*vf^4 + l1f*vf*cos(psirf)/(1-drf*p.kapparef) + l2f*axf + l3f*vf*sin(psirf) + ...
%     l4f*vf*(kappaf - p.kapparef*cos(psirf)/(1-drf*p.kapparef));

% H(tf)+1=0 Bestrafung von dr und psir im Gütefunktional
% J=tf+int(1/2*fr*dr^2+1/2*fp*psir^2+1/2*fx*ax^2+1/2*fy*kappa^2*v^4)
% H_tf = 1/2*p.fr*drf^2 + 1/2*p.fp*psirf^2 + 1/2*p.fx*axf^2 + 1/2*p.fy*kappaf^2*vf^4 + l1f*vf*cos(psirf)/(1-drf*p.kapparef) + l2f*axf + l3f*vf*sin(psirf) + ...
%     l4f*vf*(kappaf - p.kapparef*cos(psirf)/(1-drf*p.kapparef));

% sf, drf, psirf sind festgelegt, nur vf ist frei
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     srf - p.sf;...
%     drf - p.drf;...
%     psirf - p.psirf;...
%     l2f;...
%     H_tf + 1];

% nur sf ist festgelegt, vf, drf und psirf sind frei
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     srf - p.sf;...
%     l2f;...
%     l3f;...
%     l4f;...
%     H_tf + 1];

% sf und psirf sind festgelegt, vf und drf sind frei
res = [X0(1) - p.x0(1);...
    X0(2) - p.x0(2);...
    X0(3) - p.x0(3);...
    X0(4) - p.x0(4);...
    srf - p.sf;...
    psirf - p.psirf;...
    l2f;...
    l3f;...
    H_tf + 1];

% sf und drf sind festgelegt, vf und psirf sind frei, macht keinen Sinn,
% weil psirf nicht frei sein darf
% res = [X0(1) - p.x0(1);...
%     X0(2) - p.x0(2);...
%     X0(3) - p.x0(3);...
%     X0(4) - p.x0(4);...
%     srf - p.sf;...
%     drf - p.drf;...
%     l2f;...
%     l4f;...
%     H_tf + 1];
end
