function f = kangln(X,u,p)
% Bestrafung von dr im Gütefunktional
% f = [0;...
%     -2*p.fy*X(2)^3*u(2)^2 - X(5)*cos(X(4))/(1-X(3)*p.kapparef) - X(7)*sin(X(4)) - X(8)*u(2) + X(8)*p.kapparef*cos(X(4))/(1-X(3)*p.kapparef);...
%     -p.fr*X(3) - p.kapparef*X(5)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2 + p.kapparef^2*X(8)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2;...
%     X(5)*X(2)*sin(X(4))/(1-X(3)*p.kapparef) - X(7)*X(2)*cos(X(4)) - p.kapparef*X(8)*X(2)*sin(X(4))/(1-X(3)*p.kapparef)];

% Bestrafung von dr und psir im Gütefunktional
% f = [0;...
%     -2*p.fy*X(2)^3*u(2)^2 - X(5)*cos(X(4))/(1-X(3)*p.kapparef) - X(7)*sin(X(4)) - X(8)*u(2) + X(8)*p.kapparef*cos(X(4))/(1-X(3)*p.kapparef);...
%     -p.fr*X(3) - p.kapparef*X(5)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2 + p.kapparef^2*X(8)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2;...
%     -p.fpsi*X(4) + X(5)*X(2)*sin(X(4))/(1-X(3)*p.kapparef) - X(7)*X(2)*cos(X(4)) - p.kapparef*X(8)*X(2)*sin(X(4))/(1-X(3)*p.kapparef)];

% Bestrafung von psir im Gütefunktional
% f = [0;...
%     -2*p.fy*X(2)^3*u(2)^2 - X(5)*cos(X(4))/(1-X(3)*p.kapparef) - X(7)*sin(X(4)) - X(8)*u(2) + X(8)*p.kapparef*cos(X(4))/(1-X(3)*p.kapparef);...
%     -p.kapparef*X(5)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2 + p.kapparef^2*X(8)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2;...
%     -p.fpsi*X(4) + X(5)*X(2)*sin(X(4))/(1-X(3)*p.kapparef) - X(7)*X(2)*cos(X(4)) - p.kapparef*X(8)*X(2)*sin(X(4))/(1-X(3)*p.kapparef)];

% ohne Zustandsbestrafung im Gütefunktional
f = [0;...
    -2*p.fy*X(2)^3*u(2)^2 - X(5)*cos(X(4))/(1-X(3)*p.kapparef) - X(7)*sin(X(4)) - X(8)*u(2) + X(8)*p.kapparef*cos(X(4))/(1-X(3)*p.kapparef);...
    -p.kapparef*X(5)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2 + p.kapparef^2*X(8)*X(2)*cos(X(4))/(1-X(3)*p.kapparef)^2;...
    X(5)*X(2)*sin(X(4))/(1-X(3)*p.kapparef) - X(7)*X(2)*cos(X(4)) - p.kapparef*X(8)*X(2)*sin(X(4))/(1-X(3)*p.kapparef)];
end
