function dXdt = myodefun_extended(t,X,p)
v = X(1); ax = X(2); dr = X(3); psir = X(4); l1 = X(5); l2 = X(6); l3 = X(7); l4 = X(8); l5 = X(9); 
j = -l3/p.fj; kappa = -l5/(p.fy*v^3);
    dXdt = [ax;...
        j;...
        v*sin(psir);...
        kappa*v - p.kapparef*v*cos(psir)/(1-dr*p.kapparef);...
        0;...
        -(2*p.fy*kappa^2*v^3 + l1*cos(psir)/(1-dr*p.kapparef) + l4*sin(psir) + l5*kappa - l5*p.kapparef*cos(psir)/(1-dr*p.kapparef));...
        -l2;...
        -(l1*v*p.kapparef*cos(psir)/(1-dr*p.kapparef)^2 - l5*v*p.kapparef^2*cos(psir)/(1-dr*p.kapparef)^2 + p.fr*dr);...
        -(l4*v*cos(psir) - l1*v*sin(psir)/(1-dr*p.kapparef) + l5*v*p.kapparef*sin(psir)/(1-dr*p.kapparef))
        ];
end